#!/usr/bin/env groovy

node ('master') {
    stage('Build and Test') {
        env.PATH = "${tool 'Maven3'}/bin:${env.PATH}"
        checkout scm
        sh 'cd nba'
        sh 'mvn clean package'
    }
}